---@module 'spell_wordlists'
---@brief Domain vocabulary for language.nvim's `spell.extra_wordlists`.
---@description
--- General Neovim/Lua plugin-dev vocabulary (nvim, buffer, function, table, ...)
--- is already covered by language.nvim's own bundled `programming_dict`
--- (enabled below in plugins/personal/init.lua) — no need to duplicate it
--- here. This file only holds the Tricentis/TOSCA support vocabulary that
--- keeps getting flagged when writing German case notes containing English
--- product/protocol terms (`:Spellcheck de`), curated from the terminology
--- and file/folder names under $REPOS_DIR/WKDBook-Tricentis (customer names,
--- case numbers and colleague names deliberately excluded).
---
--- Split into topic lists (rather than one flat table) purely for upkeep —
--- `extra_wordlists` doesn't care, every entry is applied the same way.
--- Extend freely as new terms keep showing up in `:Spellcheck de` results.

return {
  -- Tosca product/feature vocabulary
  tosca = {
    "tosca",
    "tricentis",
    "testcase",
    "testcases",
    "teststep",
    "teststeps",
    "testsheet",
    "tbox",
    "xscan",
    "excelengine",
    "actionmode",
    "actionmodes",
    "constraint",
    "constraints",
    "module",
    "modules",
    "moduleattributes",
    "rescan",
    "merge",
    "valuerange",
    "appstack",
    "artefacts",
    "checktemplate",
    "conditions",
    "metadata",
    "contextmenu",
    "foldervariants",
    "synchronize",
    "controls",
    "controlgroups",
    "parentcontrol",
    "parentalcontrol",
    "controlproperties",
    "resultcount",
    "identifycontrols",
    "anchor",
    "anchors",
    "dex",
    "distributedexecution",
    "aos",
    "automationobjectservice",
    "xmodule",
    "xmoduleattributes",
    "textstream",
    "connectionstring",
    "multiuserworkspace",
    "standardmodules",
    "parallelblocks",
    "recoveryscenarios",
    "clickoperations",
    "closebrowser",
    "openurl",
    "explicitname",
    "dynamicvalues",
    "steeringkeywords",
    "objectexplorer",
    "regression",
    "recompilation",
    "workspace",
    "repository",
    "repositories",
    "requirement",
    "requirements",
    "cheatsheet",
    "sla",
    "servicelevelagreement",
    "wildcard",
    "wildcards",
    "commander",
  },

  -- Networking / protocol terminology (support cases involving connectivity)
  networking = {
    "ldap",
    "ldaps",
    "fqdn",
    "tld",
    "dns",
    "eof",
    "http",
    "https",
    "ssl",
    "tls",
    "rdp",
    "freerdp",
    "vnc",
    "gdi",
    "directx",
    "mcs",
    "gcc",
    "nla",
    "credssp",
    "itu",
    "remotefx",
    "urcp",
    "tcp",
    "udp",
    "localhost",
    "systemtray",
  },

  -- Tricentis/SAP support-process terminology
  support = {
    "hypercare",
    "synergy",
    "tenant",
    "mandant",
    "saas",
    "neoload",
    "confluence",
    "atlassian",
    "sap",
    "jenkins",
    "gitlab",
    "github",
    "devops",
    "grafana",
    "supportinfo",
    "logviewer",
    "servicenow",
    "snow",
    "activitystream",
    "agentworkspace",
    "escalation",
    "escalations",
    "handover",
    "handovers",
    "customization",
    "decisiontree",
    "knowledgebase",
    "exportsubset",
  },
}
