---@meta
---@module '@types.vim.uv.@types.constants'
---@brief Platform-specific constants for libuv operations

---@class uv.constants
---@field O_RDONLY integer # Open for reading only
---@field O_WRONLY integer # Open for writing only
---@field O_RDWR integer # Open for reading and writing
---@field O_APPEND integer # Append mode (writes at end of file)
---@field O_CREAT integer # Create file if it doesn't exist
---@field O_DSYNC integer # Synchronous data integrity
---@field O_EXCL integer # Error if O_CREAT and file exists
---@field O_NOCTTY integer # Don't assign controlling terminal
---@field O_NONBLOCK integer # Non-blocking I/O
---@field O_RSYNC integer # Synchronous read operations
---@field O_SYNC integer # Synchronous writes
---@field O_TRUNC integer # Truncate to zero length
---@field SOCK_STREAM integer # Stream socket (TCP)
---@field SOCK_DGRAM integer # Datagram socket (UDP)
---@field SOCK_SEQPACKET integer # Sequenced packet socket
---@field SOCK_RAW integer # Raw network protocol access
---@field SOCK_RDM integer # Reliably-delivered message
---@field AF_UNIX integer # Unix domain sockets
---@field AF_INET integer # IPv4 Internet protocols
---@field AF_INET6 integer # IPv6 Internet protocols
---@field AF_IPX integer # IPX - Novell protocols
---@field AF_NETLINK integer # Kernel user interface device
---@field AF_X25 integer # Reserved for X.25 project
---@field AF_AX25 integer # Amateur Radio AX.25
---@field AF_ATMPVC integer # ATM PVCs
---@field AF_APPLETALK integer # AppleTalk
---@field AF_PACKET integer # Packet family
---@field AI_ADDRCONFIG integer # Only return addresses for configured interfaces
---@field AI_V4MAPPED integer # Accept IPv4-mapped IPv6 addresses
---@field AI_ALL integer # Return IPv4 and IPv6 addresses
---@field AI_NUMERICHOST integer # Don't use name resolution
---@field AI_PASSIVE integer # Use wildcard IP address
---@field AI_NUMERICSERV integer # Don't use service name resolution
---@field SIGHUP integer # Hangup (1)
---@field SIGINT integer # Interrupt (2)
---@field SIGQUIT integer # Quit (3)
---@field SIGILL integer # Illegal instruction (4)
---@field SIGTRAP integer # Trace/breakpoint trap (5)
---@field SIGABRT integer # Abort (6)
---@field SIGIOT integer # IOT trap (alias for SIGABRT)
---@field SIGBUS integer # Bus error (7)
---@field SIGFPE integer # Floating point exception (8)
---@field SIGKILL integer # Kill signal (9)
---@field SIGUSR1 integer # User-defined signal 1 (10)
---@field SIGSEGV integer # Segmentation fault (11)
---@field SIGUSR2 integer # User-defined signal 2 (12)
---@field SIGPIPE integer # Broken pipe (13)
---@field SIGALRM integer # Alarm clock (14)
---@field SIGTERM integer # Termination signal (15)
---@field SIGCHLD integer # Child stopped or terminated
---@field SIGSTKFLT integer # Stack fault on coprocessor
---@field SIGCONT integer # Continue if stopped
---@field SIGSTOP integer # Stop process
---@field SIGTSTP integer # Stop typed at terminal
---@field SIGTTIN integer # Terminal input for background process
---@field SIGTTOU integer # Terminal output for background process
---@field SIGURG integer # Urgent condition on socket
---@field SIGXCPU integer # CPU time limit exceeded
---@field SIGXFSZ integer # File size limit exceeded
---@field SIGVTALRM integer # Virtual alarm clock
---@field SIGPROF integer # Profiling timer expired
---@field SIGWINCH integer # Window resize signal
---@field SIGIO integer # I/O now possible
---@field SIGPOLL integer # Pollable event (alias for SIGIO)
---@field SIGPWR integer # Power failure
---@field SIGSYS integer # Bad system call
---@field UDP_RECVMMSG integer # Enable recvmmsg support
---@field UDP_MMSG_CHUNK integer # Maximum datagrams per recvmmsg call
---@field UDP_REUSEADDR integer # Enable address reuse
---@field UDP_PARTIAL integer # Enable partial reads
---@field UDP_IPV6ONLY integer # IPv6-only mode
---@field UDP_MMSG_FREE integer # Free mmsg buffers after use
---@field TCP_IPV6ONLY integer # IPv6-only mode for TCP

return {}
