---@meta
---@module 'myoptions.@types.options'
---
--- (Detailed) Annotations for MyOptions configuration.
---   myoptions/Options_Cfg   (editor options & global toggles).

---@class HighlightColors
--- Global highlight for the active line in a window when cursorline is enabled.
--- Applied via `vim.api.nvim_set_hl(0, "CursorLine", spec)` and then referenced by
--- `winhighlight` for active windows. Typical keys: `bg`, `fg`, `bold`, `italic`, `underline`, `sp`.
--- Side-effects: none; if `color_persist = true`, it is reapplied after colorscheme changes.
---
---@field CursorLine table
---
--- Highlight for the line number of the cursor row. Mapped in `winhighlight` as `CursorLineNr:CursorLineNr`.
--- Typical keys: `fg`, `bg`, `bold`. Should contrast against the normal line numbers.
--- Side-effects: modifies perceived focus and line-number contrast in the active window.
---@field CursorLineNr table
---
--- Highlight for a vertical cursor column guide (when enabled). Applied through `winhighlight` mapping
--- `CursorColumn:CursorColumn`. Typical keys: `bg` (avoid high-contrast to reduce distraction).
--- Performance: disabled for large files if `min_colored_file_kb` threshold is exceeded.
---@field CursorColumn table
---
--- Synthetic cursor highlight group used by `guicursor` mapping when `map_cursor_to_hl = true`.
--- Typical keys: `bg`, `fg` for block/bar/underline styles. If per-mode mapping is disabled,
--- all modes may share this single group.
---@field Cursor table
---
--- Per-mode CursorLine tint used only when `enable_insert_submode_colors = true`.
--- `CursorLineN` is the tint for Normal-like modes. Applied via dynamic `winhighlight`.
---@field CursorLineN table
---
--- Per-mode CursorLine tint for Insert-like modes.
---@field CursorLineI table
---
--- Per-mode CursorLine tint for Visual/Select modes (V, v, CTRL-V).
---@field CursorLineV table
---
--- Per-mode CursorLine tint for Replace/Virtual Replace/Replace-Pending modes.
---@field CursorLineR table
---
--- Per-mode cursor face used by `guicursor` when both `map_cursor_to_hl = true`
--- and `enable_insert_submode_colors = true`. Applied globally via `:set guicursor`.
--- Use with care on TUI-only setups; will fall back gracefully if unsupported.
---@field CursorNormal table
---
--- Insert-mode cursor face (see `CursorNormal` remarks).
---@field CursorInsert table
---
--- Visual-mode cursor face (see `CursorNormal` remarks).
---@field CursorVisual table
---
--- Replace-mode cursor face (see `CursorNormal` remarks).
---@field CursorReplace table
---
--- Short-lived highlight for yanked regions. Used by the TextYankPost autocmd.
--- Typical keys: `bg` (solid wash). Timeout controlled by code (~150ms).
--- Side-effects: none; purely visual feedback.
---@field YankFlash table
---
--- Short-lived highlight for pasted regions. Fired by custom `p`/`P` mappings
--- when `enable_put_flash` and `map_put_flash` are on. Typical keys: `bg`.
---@field PutFlash table
---
--- SignColumn tint applied when the worst diagnostic severity is "Error".
--- Mapped into `winhighlight` as `SignColumn:SignColError`. Use a subtle `bg`.
---@field SignColError table
---
--- SignColumn tint for "Warn" severity.
---@field SignColWarn table
---
--- SignColumn tint for  "Info" severity.
---@field SignColInfo table
---
--- SignColumn tint for HINT severity.
---@field SignColHint table
---
--- Neutral SignColumn fallback when there are no diagnostics or tinting is disabled.
---@field SignColNeutral table
---
--- Terminal window baseline face. Applied for terminal buffers (TermOpen) through `winhighlight` as `Normal:TermNormal`.
--- Helps unify terminal background with the editor theme.
---@field TermNormal table
---
--- Terminal window cursorline tint. Applied via `winhighlight` as `CursorLine:TermCursorLine`.
--- Usually a subtle background distinct from `TermNormal`.
---@field TermCursorLine table
---
--- Underline-only (recommended) highlight used by the “current word under cursor” helper.
--- Keep low-noise: use `underline = true` without background to avoid flicker/visual clutter.
---@field CursorWord table
---
--- Face for matched parentheses/flashing. Used together with `enable_matchparen` (in Options).
--- Keep it subtle (e.g., faint background or bold) to avoid disrupting reading flow.
---@field MatchParen table
---
---@field IndentScope    table  -- full-line bg for active indentation block

---@class OptionsCfg
---
--- Enables subtle matchparen “blink” of matching pairs.
--- Changes:
---   * Sets `vim.opt.showmatch` accordingly.
---   * Uses `matchtime_tenths` for blink duration.
--- Side-effects: tiny focus cue when moving over brackets; can be disabled if distracting.
---@field enable_matchparen boolean
---
--- Blink duration for the matchparen feature in tenths of a second.
--- Changes:
---   * Applied to `vim.opt.matchtime`; e.g., `2` ≙ ~200ms.
--- Side-effects: longer values increase visibility but may feel intrusive.
---@field matchtime_tenths integer

return {}
