---@meta
---@module 'config.neotree.@types.node'
---@brief Neo-tree node structure definition
---@description
--- Represents a single entry (file, directory, virtual) within a Neo-tree source.
--- This is the core data structure for tree navigation and manipulation.

---@class Cfg.NeoTree.Node
---@field id string Unique node identifier (usually absolute path)
---@field path string|nil Filesystem path if applicable
---@field name string Display name of the node
---@field type Cfg.NeoTree.NodeType Node classification
---@field parent_id string|nil ID of the parent node (nil for root)
---@field level integer Tree depth (root = 0)
---@field loaded boolean Whether children have been loaded
---@field is_expanded boolean|nil Directory expansion state
---@field has_children boolean|nil Whether node has child entries
---@field children Cfg.NeoTree.Node[]|nil Child nodes if loaded
---@field extra table|nil Source-specific metadata
---@field tree Cfg.NeoTree.Tree Reference to containing tree
---@field explicitly_marked_node_ids table<string, boolean>|nil Marked nodes for batch operations
---@field is_directory fun(self: Cfg.NeoTree.Node): boolean
---@field is_file fun(self: Cfg.NeoTree.Node): boolean
---@field get_parent_id fun(self: Cfg.NeoTree.Node): string|nil
---@field get_path fun(self: Cfg.NeoTree.Node): string|nil
---@field get_name fun(self: Cfg.NeoTree.Node): string
--- Optional fields used by some Neo-tree versions / sources
---@field line integer|nil  -- 1-based line number in buffer
---@field row integer|nil   -- 0-based line number in buffer
---@field position {line: integer, col: integer}|nil  -- cursor position
---@field range {start: {line: integer, col: integer}, ["end"]: {line: integer, col: integer}}|nil
---@field get_id fun(self: Cfg.NeoTree.Node): string
---@field uri string|nil

return {}
