---@meta
---@module 'lib.normalize.types'
---@brief Type definitions for the normalize library
---@description
--- This module defines all type annotations for lib.normalize, providing comprehensive
--- type information for normalization functions, validators, and schema-driven configuration.

---@class Lib.Normalize.StringListOpts
--- Configuration options for string list normalization.
---@field sep string|nil Separator pattern (default: "[%s,]+")
---@field trim boolean|nil Whether to trim whitespace from tokens
---@field dedup boolean|nil Whether to deduplicate entries

---@class Lib.Normalize
---@field utils Lib.Normalize.Utils
---@field validators Lib.Normalize.Validators

---@class Lib.Normalize.All
--- Main normalization toolkit providing type coercion, validation, and schema-driven config merging.
--- All to_* functions are side-effect free and return nil on invalid input.
--- All apply_* functions mutate the provided table and return boolean success status.
---
-- =========================================================
-- Direct Value Normalizers (Pure Functions)
-- =========================================================
---
---@field to_bool fun(v: any): boolean|nil
--- Convert value into a boolean using loose parsing rules.
--- Accepts: booleans directly, numbers 0/1, strings "true/false/yes/no/on/off/1/0" (case-insensitive).
--- Returns nil for any value that cannot be interpreted as boolean.
---
---@field to_int fun(v: any, min?: integer, max?: integer): integer|nil
--- Convert value to integer with optional clamping to [min, max] range.
--- Truncates towards zero for non-integer numbers.
--- Returns nil if conversion fails.
---
---@field to_float fun(v: any, min?: number, max?: number, precision?: integer): number|nil
--- Convert value to float with optional clamping and precision rounding.
--- precision: Number of fractional digits to keep (>=0), nil = no rounding.
--- Returns nil if conversion fails.
---
---@field to_string fun(v: any, allow_empty?: boolean, do_trim?: boolean): string|nil
--- Return string if non-empty, optionally trimming whitespace.
--- allow_empty: If false/nil, empty strings return nil.
--- do_trim: If true, trim leading/trailing whitespace.
---
---@field to_enum fun(v: any, allowed: Lib.Normalize.StringList, case_insensitive?: boolean): string|nil
--- Map a value to an enum entry, matching against allowed values.
--- By default performs case-insensitive matching; returns original allowed value on match.
--- Returns nil if no match found.
---
---@field to_string_list fun(v: any, opts?: Lib.Normalize.StringListOpts): Lib.Normalize.StringList|nil
--- Convert value into a list of strings.
--- Accepts strings (split by separator) or tables (filtered to string entries).
--- Empty results return nil.
---
---@field to_argv fun(v: any): Lib.Normalize.StringList|nil
--- Convert shell-like command string or argv table into argv format.
--- Supports simple double-quoted segments; does not resolve escapes comprehensively.
--- Returns nil if any array element is non-string or empty.
---
---@field to_diagnostic_severity fun(v: any): integer|nil
--- Map user severity to vim.diagnostic.severity constant.
--- Accepts: "error/err", "warn/warning", "info", "hint", "all"/"" (returns nil for all/empty).
--- Numeric values pass through unchanged.
---
---@field to_log_level fun(v: any): integer|nil
--- Map user log level to vim.log.levels constant.
--- Accepts: "trace", "debug", "info", "warn", "error", "off" (returns nil for off).
--- Numeric values pass through unchanged.
---
---@field to_path fun(v: any, type_filter?: string, must_exist?: boolean): string|nil
--- Normalize filesystem path and optionally verify existence and type.
--- type_filter: Required path type: "file", "directory", or nil (any type).
--- must_exist: If true, path must exist and match type_filter.
--- Uses vim.fs.normalize when available, otherwise provides fallback normalization.
---
-- =========================================================
-- Validators with (ok, val, err) Pattern
-- =========================================================
---
---@field as_int fun(name: string, v: any, min: integer, allow_nil: boolean): boolean, integer|nil, string|nil
--- Validate that a value is an integer meeting minimum bound requirements.
--- Returns: (ok, val, err)
--- Contract:
---   • nil + allow_nil=true  → ok=true, val=nil, err=nil (caller keeps default)
---   • nil + allow_nil=false → ok=false, val=nil, err="<name> is required"
---   • non-integer           → ok=false, err="<name> must be an integer"
---   • value < min           → ok=false, err="<name> must be ≥ <min>"
---   • otherwise             → ok=true, val=<integer>, err=nil
---
---@field as_bool fun(name: string, v: any): boolean, boolean|nil, string|nil
--- Validate that a value is strictly boolean (true/false).
--- Returns: (ok, val, err)
--- Only Lua booleans are accepted; strings like "true"/"false" are NOT coerced.
--- For permissive conversion, use to_bool() + apply_bool_loose().
---
---
-- =========================================================
-- Utility Functions
-- =========================================================
---
---@field trim fun(s: any): string
--- Trim leading and trailing ASCII whitespace from string.
--- Returns empty string if input is not a string.
---
---@field clamp fun(n: number, min?: number, max?: number): number
--- Clamp number into [min, max] range (inclusive).
--- Nil min/max values are ignored.
---
---@field coalesce fun(...: any): any
--- Return the first non-nil argument.
--- Returns nil if all arguments are nil.
---
---@field normalize_path fun(p: any): string
--- Normalize filesystem path using Neovim facilities if available.
--- Uses vim.fs.normalize when present, otherwise provides fallback that:
---   • Collapses consecutive slashes
---   • Strips trailing slash (except for root)
--- Returns empty string if input is invalid.
---
---@field path_kind fun(p: string): string
--- Determine path type using libuv if available.
--- Returns: "file", "directory", or "" (does not exist/unavailable).
---
---@field dedup_strings fun(list: Lib.Normalize.StringList): Lib.Normalize.StringList
--- Deduplicate string list while preserving first occurrence order.
--- Non-string entries are filtered out.

return {}
