---@module 'autocmds.patches.types'
---@brief Comprehensive type definitions for the automatic patch system.
---@description
--- This module defines all types used across the patch system.
--- Types are organized by functional area: entries, results, status, config.

-- #####################################################################
-- Core Patch Entry

---@class PatchEntry
--- Unique identifier for this patch (must be globally unique across all patches).
--- Used for status tracking and selective application.
---@field key string
---
--- Repository/plugin name (e.g., "gitsigns.nvim", "noice.nvim").
--- If nil, auto-detected from target path (looks for ~/.local/share/nvim/lazy/<repo>).
---@field repo string|nil
---
--- Absolute path to the .diff or .patch file.
--- Must be readable and contain a valid unified diff.
---@field patch string
---
--- Absolute path to the target file that will be patched.
--- Must exist and be writable.
---@field target string
---
--- Optional patch strip level (passed as -p<N> to patch command).
--- Default: 0 (no path stripping).
--- Typical values: 0, 1, 2.
---@field strip integer|nil
---
--- Priority value for ordering patches (higher = applied earlier).
--- Useful when patches have dependencies or when order matters.
--- Default: 0.
---@field priority integer|nil
---
--- Whether this patch is enabled (false = skipped).
--- Default: true.
---@field enabled boolean|nil

---@alias PatchTable PatchEntry[]

-- #####################################################################
-- Patch Results

---@alias PatchStatusType
--- Patch has never been attempted in this session.
---| "never_tried"
--- Patch was already applied (detected via reverse dry-run), skipped.
---| "already_applied"
--- Patch was successfully applied in this run.
---| "applied"
--- Patch application failed (see message for details).
---| "failed"
--- Patch is disabled via enabled=false, not attempted.
---| "disabled"

---@class PatchResult
--- Unique key of the patch.
---@field key string
---
--- Repository name (auto-detected or explicit).
---@field repo string
---
--- Whether the patch is enabled.
---@field enabled boolean
---
--- Whether patch application succeeded.
---@field success boolean
---
--- Current status of the patch.
---@field status PatchStatusType
---
--- Optional human-readable message (error details, skip reason, etc.).
---@field message string|nil
---
--- Timestamp of when this result was recorded (ISO 8601).
---@field timestamp string
---
--- Duration of the operation in milliseconds (nil if not attempted).
---@field duration_ms number|nil

-- #####################################################################
-- Validation Results

---@class ValidationResult
--- Whether validation passed.
---@field valid boolean
---
--- Optional error message if validation failed.
---@field error string|nil
---
--- Whether patch is already applied (from dry-run check).
---@field already_applied boolean|nil

-- #####################################################################
-- Status Management

---@class StatusQuery
--- Filter by repository names.
---@field repos string[]|nil
---
--- Filter by patch keys.
---@field keys string[]|nil
---
--- Filter by status types.
---@field status_filter PatchStatusType[]|nil

---@class StatusEntry
--- Unique key.
---@field key string
---
--- Repository name.
---@field repo string
---
--- Last known status.
---@field status PatchStatusType
---
--- Last status message.
---@field message string|nil
---
--- Timestamp of last update (ISO 8601).
---@field last_updated string
---
--- Number of times this patch was attempted.
---@field attempt_count integer
---
--- SHA256 checksum of the patch file content (to detect modifications).
---@field checksum string|nil

-- #####################################################################
-- Configuration

---@class PatchConfig
--- Maximum number of concurrent patch operations.
--- Higher values = faster processing but more resource usage.
--- Default: 3.
---@field max_concurrency? integer
---
--- Timeout per patch operation in milliseconds.
--- Default: 30000 (30 seconds).
---@field timeout_ms? integer
---
--- Whether to enable verbose logging (DEBUG level).
--- Default: false.
---@field verbose? boolean
---
--- Whether to show notifications for patch results.
--- Default: true (only for failures and final summary).
---@field notify? boolean
---
--- Delay after LazyUpdate event before applying patches (ms).
--- Gives Lazy.nvim time to finish file operations.
--- Default: 500.
---@field lazy_update_delay_ms? integer

-- #####################################################################
-- Logging

---@class LogEntry
--- Log level.
---@field level LogLevel
---
--- Log message.
---@field message string
---
--- Timestamp (ISO 8601).
---@field timestamp string
---
--- Optional context data (patch key, repo, error details, etc.).
---@field context table|nil

-- #####################################################################
-- Error Types

---@class PatchError
--- Error type identifier.
---@field type "PatchValidationError"|"PatchApplicationError"|"PatchIOError"
---
--- Human-readable error message.
---@field message string
---
--- Patch key that caused the error.
---@field key string
---
--- Optional context (file paths, command output, etc.).
---@field context table|nil
