---@module 'custom.lua_project_file_stats.types'
---@brief Type definitions for Lua Project File Statistics

---@alias LuaProjectFileStats.PercentMode
---| "both"    # Show both numbers and percentages
---| "percent" # Show only percentages
---| "numbers" # Show only numbers

---@class LuaProjectFileStats.DefaultConfig
---Configuration presets for default command behavior.
---Used at the top of init.lua to control what gets analyzed and displayed
---without modifying the core logic.
---@field lua_files boolean Analyze Lua files (main feature)
---@field misc_files boolean Analyze non-Lua files (Markdown, TXT, JSON)
---@field show_file_tables boolean Print detailed file-level statistics tables
---@field show_folder_tables boolean Print folder summary tables
---@field show_total_summary boolean Print total summary table
---@field show_ratios boolean Show ratio analysis (comment%, annotation%, etc.)
---@field show_deviations boolean Show deviations from global averages
---@field show_top_lists boolean Show top-N lists (largest files/folders)
---@field show_misc_detailed boolean Show detailed list of non-Lua files
---@field percent_mode LuaProjectFileStats.PercentMode Display mode for values
---@field reverse_order boolean Reverse output order (summary first)
---@field top_n integer Number of items in top-N lists
---@field exclude_type_files_from_ratios boolean Exclude type definition files from ratio analysis

---@class LuaProjectFileStats.Config
---Runtime configuration passed to analyze function.
---Constructed from command-line args or user commands.
---@field root_dir string Root directory to analyze
---@field reverse_order boolean Reverse output order (summary first)
---@field percent_mode LuaProjectFileStats.PercentMode Display mode
---@field fields_to_print string[] List of sections to print: "files", "folders", "summary"
---@field single_file_path string|nil Path for single file analysis
---@field col_width integer Column width in tables
---@field top_n integer Number of items in top-N lists
---@field only_top_files_lines boolean Show ONLY top files by lines
---@field only_top_files_words boolean Show ONLY top files by words
---@field show_ratios boolean Show ratio analysis
---@field show_deviations boolean Show deviations from averages
---@field output_file string|nil Path to save output
---@field interactive boolean Interactive mode (reserved for future use)
---@field async boolean Use async execution in Neovim
---@field analyze_lua boolean Analyze Lua files
---@field analyze_misc boolean Analyze miscellaneous files
---@field show_misc_detailed boolean Show detailed misc file listing

---@class LuaProjectFileStats.Stats
---Statistics for a single file or aggregated group.
---@field total_lines integer Total line count
---@field lines_without_comments integer Code lines (excluding comments)
---@field comment_lines integer Lines containing comments
---@field lines_without_annotations integer Code lines (excluding annotations)
---@field annotation_lines integer Lines containing LuaLS annotations
---@field blank_lines integer Whitespace/blank lines
---@field total_words integer Total word count
---@field words_in_comments integer Words in comments
---@field words_in_annotations integer Words in annotations
---@field words_without_comments integer Words in code only
---@field words_without_annotations integer Words in code (excluding annotations)
---@field words_in_blank integer Words in blank lines (usually 0)
---@field total_files integer|nil Number of files (only in aggregated stats)

---@class LuaProjectFileStats.FileInfo
---Information about a single analyzed file.
---@field rel_file string Relative path from cwd
---@field stats LuaProjectFileStats.Stats File statistics

---@class LuaProjectFileStats.FolderStats : LuaProjectFileStats.Stats
---Extended statistics for a folder.
---@field file_count integer Number of files in folder
---@field files LuaProjectFileStats.FileInfo[] List of files in folder

---@class LuaProjectFileStats.Ratios
---Computed ratio metrics for code quality analysis.
---@field comment_ratio number Comment lines / total lines
---@field annotation_ratio number Annotation lines / total lines
---@field doc_ratio number (Comments + annotations) / total lines
---@field code_ratio number Code lines / total lines
---@field avg_lines_per_file number Total lines / file count
---@field annotation_to_comment_ratio number Annotations / comments

---@class LuaProjectFileStats.State
---Global analysis state containing all results.
---@field folder_summary table<string, LuaProjectFileStats.FolderStats> Lua folder statistics
---@field total_stats LuaProjectFileStats.Stats Aggregated Lua statistics
---@field global_averages LuaProjectFileStats.Ratios Average ratios across folders
---@field output_buffer string[] Lines collected for file output
---@field cwd string Current working directory
---@field misc_files MiscFilesState|nil Statistics for non-Lua files
