---@meta
---@module 'lib.@types.all_functions'

-- =========================================================
-- All Exported Lib Functions
-- =========================================================
---@class Lib
---
--- === Editor Interfaces / Interaction Layers ===
--- Autocmd/Keymaps
---@field group fun(name: string, clear: boolean|nil): integer # Create autocommand group
---@field create fun(event: string|string[], callback: fun(args:Lib.Autocmd.Args), opts: LibAutocmdOpts|nil): nil # Create autocommand
---@field get_augroup fun(name: string, opts: { clear?: boolean, prefix?: string }|nil): integer # Augroup registry: Centralized augroup creation with optional prefixing and deduplication.
--- Map
---@field map fun(modes: string|string[], lhs: string, rhs: string|function, opts: Lib.Map.Opts|nil, desc: string?): nil # Keymap helper
--- Usrcmd
---@field create fun(name: string, callback: string|fun(args:Lib.UserCommand.Args), opts: LibUserCommandOpts|nil): nil
------
--- === Cross-Platform ===
---@field is_windows fun(): boolean # returns true if corrent os is windows
---@field is_wsl fun(): boolean # returns true if corrent os is wsl
---@field is_macos fun(): boolean # returns true if corrent os is macos
---@field is_linux fun(): boolean # returns true if corrent os is linux
---@field is fun(platform?: Lib.Cross.Platform.PlatformName): boolean|Lib.Cross.Platform.PlatformName # Dual behavior: returns platform name or boolean check
-- Lib.Cross.Run
---@field shell fun(): OsShell # Pick a shell suitable for the platform
---@field run fun(cmd: string, cb: fun(ok:boolean, res:OsRunResult): nil): nil # Async run using vim.system when available; falls back to jobstart
---@field run_blocking fun(cmd: string): OsRunResult # Blocking run (utility for quick conversions / probing)
---Lib.Cross.CopyToClipboard
---@field copy_to_clipboard fun(text: string): boolean # Copy text to system clipboard using platform-appropriate backend
---
-- =========================================================
--- === Filesystem ===
-- =========================================================
--
---@field find_upward_dir fun(names: string[], from: string): string|nil # Find directory containing files
---@field dedup fun(entries: string[]): string[] # Deduplicate filesystem paths
---@field path_shorten fun(path: string, max_len: integer): string # Shorten path for display
---Lib.Fs.Path
---@field joinpath fun(parts: string[]): string # Joins variable strings to one path
---@field ensure_dir fun(path: string): boolean, string? # Ensure directory exists
---@field is_subpath fun(path: string, base: string): boolean # Check if path is subpath of base
---@field is_dir fun(p: string): boolean # Check if path is a directory
---@field relpath fun(path: string, base: string): string # Compute relative path
---
--- === Require ===
---@field require_safe fun(name: string): boolean, any # Safe require with structured error handling
---@field require_dir fun(dir: string, calls?: string|string[]|""): nil # Load all modules in a directory
---@field require_lazy fun(module_name: string): fun(): table # Lazy-loading wrapper
---
-- =========================================================
--- === Buffer ===
-- =========================================================
--
---@field is_markdown_buf fun(bufnr_arg: integer|nil): integer|nil # Returns buffer number if valid markdown buffer
---@field insert_lines fun(lines: string[], pos?: Lib.Buf.InsertLinesPos): nil # Insert lines into buffer
---
-- =========================================================
-- === BufWinTab
-- =========================================================
--
-- Buffer Utils (Flattened)
--
---@field DEFAULT_EXCLUDE_FILETYPES string[] # Standard exclusion list for "real" buffer counting
---@field count_listed_buffers fun(): integer # Count all listed buffers
---@field get_buffer_info fun(bufnr: number): BufInfo # Get metadata for single buffer
---@field count_real_listed_buffers fun(exclude_filetypes?: string[]): integer # Count listed buffers excluding plugins
---@field list_all_buffers_info fun(): BufInfo[] # Get metadata for all buffers
---@field list_listed_buffers_info fun(): BufInfo[] # Get metadata for listed buffers
---@field format_buffers_table fun(buftable: BufInfo[]): string # Format buffer table to string
---@field print_buffers_table fun(buftable: BufInfo[]): nil # Print buffer table to command line
---@field collect_all_buffer_info fun(): BufCollectedInfo # Aggregate all buffer information
---@field print_summary fun(): nil # Print buffer summary to command line
--
-- Window Utils (Flattened)
--
---@field count_listed_buffers_win fun(): integer # Count listed buffers (windows_utils version)
---@field list_all_buffers_info_win fun(): WinInfo[] # Get extended metadata for all buffers
---@field get_listed_buffer_ids fun(): integer[] # Get array of listed buffer IDs
---@field get_buffers_grouped_by_filetype fun(): table<string, integer[]> # Group buffers by filetype
---@field get_current_buffer_info fun(): WinInfo # Get current buffer metadata
---@field get_tabpage_buffers fun(tabnr?: integer): integer[] # Get buffers in tabpage
---@field format_buffers_report fun(): string # Format compact buffer report
---@field collect_all_state fun(): AggregatedState # Collect comprehensive state
---@field show_aggregated_state fun(silent?: boolean): string|nil # Print or return state
---@field collect_win_report fun(winid?: integer): WinReport # Collect window inspection report
--
-- Tab Utils (Flattened)
--
---@field list_tabs fun(): TabInfo[] # List all tabpages with metadata
---@field format_tab_one_line fun(info: TabInfo): string # Format tabpage to one line
---@field print_tabs fun(tabs?: TabInfo[]): nil # Pretty-print tabpages
---@field get_current_tab fun(): TabInfo|nil # Get current tabpage metadata
---@field get_tab_by_number fun(tabnr: integer): TabInfo|nil # Find tabpage by number
---@field is_single_tab fun(): boolean # Check if only one tab open
---@field collect_report fun(): TabReport # Collect tabpage report
--
-- =========================================================
-- Resize Guarded (Flattened)
-- =========================================================
--
---@field create_resize_callback fun(cmd: string, exclude_filetypes?: string[], exclude_names?: string[], lhs?: string): ResizeCallback # Create guarded resize callback
--
-- =========================================================
-- Capture (Flattened)
-- =========================================================
--
---@field capture_buf_win fun(cmd: string, opts?: BufWinCapture.Opts, cb?: fun(result: BufWinCapture.Results)): BufWinCapture.Results|nil # Capture buffers/windows after command
--
-- =========================================================
-- Safe Adjacent Buffer (Flattened)
-- =========================================================
--
---@field save_last_normal_buffer fun(): nil # Force-save last normal file buffer
--
-- =========================================================
-- Move current buffer to new tab
-- =========================================================
--
---@field move_current_buffer_to_new_tab Lib.BufWinTab.MoveBufToTab
---
-- =========================================================
-- Meta
-- =========================================================
--
---@field noop fun(): nil # No-operation function. Explicitly does nothing and returns nil.
---@field identity fun(v: any): any # Identity function. Returns the value it was given unchanged. Commonly used in functional pipelines as a default mapper or when a transformation hook is optional.
---@field always_true fun(): boolean # Constant-true predicate. Always returns true regardless of input. Useful as a default filter or guard function.
---@field always_false fun(): boolean # Constant-false predicate. Always returns false regardless of input. Useful as a disabling predicate or sentinel.
---@field const fun(value: any): fun(): any # Constant value generator. Returns a function that always yields the provided value. Useful for lazy defaults, dependency injection, or testing.
---@field raise fun(err: any): nil # Error passthrough helper. Always throws an error. LuaLS has no `never` type, so `nil` is used as a pragmatic substitute.
--
---
--- === Tables ===
---@field with fun(base: table|nil, extra: table|nil): table # Merge two option tables
---@field array table # Array utilities
---@field core table # Core table utilities
---@field dict table # Dictionary utilities
---@field set table # Set utilities
---@field functional table # Functional helpers
---@field safe table # Safe table operations
---
--- === Strings ===
---@field strings Lib.Strings.ALL # All string functions
---@field trim fun(s: any): string # Trim whitespace
---@field slugify fun(s: string): string # Convert to slug
---@field kebab_case fun(s: string): string # Convert to kebab-case
---@field starts_with fun(s: string, prefix: string): boolean # Check string prefix
---@field ends_with fun(s: string, suffix: string): boolean # Check string suffix
---@field contains fun(s: string, needle: string): boolean # Check if string contains
---@field split fun(s: string, sep: string): string[] # Split string
---@field join fun(parts: string[], sep: string): string # Join strings
---@field replace_all fun(s: string, from: string, to: string): string # Replace all occurrences
---@field capitalize fun(s: string): string # Capitalize first letter
---@field uncapitalize fun(s: string): string # Uncapitalize first letter
---@field snake_case fun(s: string): string # Convert to snake_case
---@field camel_case fun(s: string): string # Convert to camelCase
---@field pad_start fun(s: string, width: integer): string # Pad string start
---@field pad_end fun(s: string, width: integer): string # Pad string end
---@field pad_center fun(s: string, width: integer): string # Pad string center
---@field indent fun(s: string, n: integer): string # Indent string
---@field dedent fun(s: string): string # Dedent string
---@field is_empty_or_space fun(s: any): boolean # Check if empty or whitespace
---@field remove_prefix fun(s: string, list?: string[]): string # Remove common prefixes
---@field uri_decode fun(s: string): string # Decode URI
---@field normalize_anchor fun(s: string): string # Normalize anchor
---@field has_scheme fun(s: string): boolean # Check if URL has scheme
---@field is_web_url fun(s: string): boolean # Check if web URL
---@field url_under_cursor fun(line: string, col: integer): string|nil # Get URL under cursor
---@field escape_lua_magic fun(s: string): string # Escape Lua pattern magic
---@field find_plain fun(s: string, needle: string): integer|nil, integer|nil # Plain string find
---@field replace_plain fun(s: string, from: string, to: string): string # Plain string replace
---@field surround fun(s: string, left: string, right: string): string # Surround string
---@field hex_to_string fun(hex: string): string # Convert hex to UTF-8 string
---
--- === Terminal ===
---@field terminal_escape fun(path: string): string # Cross-platform path escaping
---@field is_terminal_buf fun(bufnr: integer): boolean|nil # Checks if buffer is terminal
---@field delete_terminal_buf fun(bufnr: integer): boolean|nil # Deletes terminal buffer
---
--- === UI ===
--- Hover Select
---@field hover_select Lib.UI.HoverSelect # Hover select module
--- HL
---@field namespace fun(name: string): integer
---@field set fun(group: string, opts: Lib.Highlight.Opts, ns: string|integer|nil)-
---
--- === Notify ===
---@field notify table # Notification utilities
---@field resolve_log_level fun(level?: LogLevel, default?: LogLevelNumber): integer # Resolve log level
---
--- === Lazy ===
---@field lazy table # Lazy loading utilities
---
--- === Memo ===
---@field memo table # Memoization utilities
---
--- === Time ===
---@field time_diff fun(): Lib.Time.TimeDiff # Create time diff instance
---
--- === Normalize ===
---@field normalize table # Normalization utilities
---
--- === Nvim ===
---@field simple_echo fun(msg: string, hl: string|nil, is_error: boolean|nil): integer|string # This module returns a single function that echoes messages using vim.api.nvim_echo
---
--- === JSON ====
---
--- Decode
---
---@field is_array_like fun(v: any): boolean # Prüft, ob ein Wert eine array-ähnliche Tabelle ist. Erlaubt sind ausschließlich zusammenhängende positive Integer-Keys beginnend bei 1 (Lua-Array-Semantik). Gibt false für Maps, Sparse-Arrays oder Nicht-Tabellen zurück
---
---@field table_to_string_array fun(tbl: table): string[] # Konvertiert eine Tabelle in ein `string[]`.
--- * Array-ähnliche Tabellen: jedes Element wird per `tostring` übernommen.
--- * Nicht-array-ähnliche Tabellen: Keys werden stabil sortiert und
---   als `"key: value"`-Strings serialisiert.
--- * Verschachtelte Tabellen werden mittels `vim.inspect` dargestellt.
---
---@field ensure_string_array fun(v: any): string[] # Erzwingt ein `string[]` aus beliebigem Input.
--- * table   → `table_to_string_array`
--- * string  → Aufteilung an Newlines (`vim.split`)
--- * scalar  → Einzel-Array mit `tostring(v)`
--- Garantiert immer ein nicht-nil `string[]`.

return {}
