---@meta
---@module 'lib.@types.all_functions'

-- =========================================================
-- All Exported Lib Functions
-- =========================================================
---@class Lib
---
--- === Editor Interfaces / Interaction Layers ===
---
-- =========================================================
--- Autocmd/Keymaps
-- =========================================================
--
---@field augroup_create_clear Lib.AutoCmd.AuGroup.Create
---@field group fun(name: string, clear: boolean|nil): integer # Create autocommand group
---@field create fun(event: string|string[], callback: fun(args:Lib.Autocmd.Args), opts: LibAutocmdOpts|nil): nil # Create autocommand
---@field get_augroup fun(name: string, opts: { clear?: boolean, prefix?: string }|nil): integer # Augroup registry: Centralized augroup creation with optional prefixing and deduplication.
---@field norm_events fun(ev: any, fallback: string[]): string[] # Normalize event configuration to a non-empty list.
---@field norm_pattern fun(pat: any): string|string[] # Normalize an autocmd pattern field.
---
-- =========================================================
--- Map
-- =========================================================
--
---@field map fun(modes: string|string[], lhs: string, rhs: string|function, opts: Lib.Map.Opts|nil, desc: string?): nil # Keymap helper
---
-- =========================================================
--- Usrcmd
-- =========================================================
--
---@field create fun(name: string, callback: string|fun(args:Lib.UserCommand.Args), opts: LibUserCommandOpts|nil): nil
---
-- =========================================================
--- === Cross-Platform ===
---
-- =========================================================
---@field is_windows fun(): boolean # returns true if corrent os is windows
---@field is_wsl fun(): boolean # returns true if corrent os is wsl
---@field is_macos fun(): boolean # returns true if corrent os is macos
---@field is_linux fun(): boolean # returns true if corrent os is linux
---@field is fun(platform?: Lib.Cross.Platform.PlatformName): boolean|Lib.Cross.Platform.PlatformName # Dual behavior: returns platform name or boolean check
---
-- =========================================================
-- Lib.Cross.Run
-- =========================================================
--
---@field shell fun(): OsShell # Pick a shell suitable for the platform
---@field run fun(cmd: string, cb: fun(ok:boolean, res:OsRunResult): nil): nil # Async run using vim.system when available; falls back to jobstart
---@field run_blocking fun(cmd: string): OsRunResult # Blocking run (utility for quick conversions / probing)
---
-- =========================================================
---Lib.Cross.CopyToClipboard
-- =========================================================
--
---@field run_blocking fun(cmd: string[], input?: string): boolean, string|nil # Low-level argv-based process runner with stdin support.
---@field copy_to_clipboard fun(text: string): boolean # Copy text to system clipboard using platform-appropriate backend
---
-- =========================================================
--- === Filesystem ===
-- =========================================================
--
---@field find_upward_dir fun(names: string[], from: string): string|nil # Find directory containing files
---@field dedup fun(entries: string[]): string[] # Deduplicate filesystem paths
---@field path_shorten fun(path: string, max_len: integer): string # Shorten path for display
---Lib.Fs.Path
---@field joinpath fun(parts: string[]): string # Joins variable strings to one path
---@field ensure_dir fun(path: string): boolean, string? # Ensure directory exists
---@field is_subpath fun(path: string, base: string): boolean # Check if path is subpath of base
---@field is_dir fun(p: string): boolean # Check if path is a directory
---@field relpath fun(path: string, base: string): string # Compute relative path
--- Lib.fs.write
---@field write_to_file fun(path: string, content: string): boolean, string|nil # Write string content to given path. Makes sure that directory exists. Return sucess boolean and in cade of no success string notice
---
-- =========================================================
--- === Require ===
-- =========================================================
--
---@field require_safe fun(name: string): boolean, any # Safe require with structured error handling
---@field require_dir fun(dir: string, calls?: string|string[]|""): nil # Load all modules in a directory
---@field require_lazy fun(module_name: string): fun(): table # Lazy-loading wrapper
---
-- =========================================================
--- === Git ===
-- =========================================================
---
---@field in_git_repo fun(git_cmd: string): boolean # Check if current directory is inside a Git work-tree.
---@field repo_root fun(git_cmd?:string):string|nil # Get the absolute path to the repository root.
---@field current_branch fun(git_cmd?:string):string|nil # Get the current branch name. Returns nil in detached HEAD state.
---@field is_detached_head fun(git_cmd?:string):boolean # Check whether the repository is in a detached HEAD state.
---@field is_dirty fun(git_cmd?:string):boolean # Check whether the working tree has uncommitted changes.
---@field is_tracked fun(path:string, git_cmd?:string):boolean # Check whether the given path is tracked by Git.
---@field upstream fun(git_cmd?:string):string|nil # Get the upstream branch of the current branch.
---@field ahead_behind fun(git_cmd?:string):(boolean, boolean) # Check whether the current branch is ahead or behind its upstream.
---@field head_short_hash fun(git_cmd?:string):string|nil # Get the short hash of HEAD.
---@field clear_line_diff fun(ns:integer):fun(buf:integer):nil # Create a buffer-scoped function that clears all virtual text in the given namespace. This function binds the namespace once and returns a callback suitable for autocmd usage.
---
-- =========================================================
--- === Buffer ===
-- =========================================================
--
---@field is_markdown_buf fun(bufnr_arg: integer|nil): integer|nil # Returns buffer number if valid markdown buffer
---@field insert_lines fun(lines: string[], pos?: Lib.Buf.InsertLinesPos): nil # Insert lines into buffer
---
-- =========================================================
-- === BufWinTab
-- =========================================================
--
-- Buffer Utils (Flattened)
--
---@field DEFAULT_EXCLUDE_FILETYPES string[] # Standard exclusion list for "real" buffer counting
---@field count_listed_buffers fun(): integer # Count all listed buffers
---@field get_buffer_info fun(bufnr: number): BufInfo # Get metadata for single buffer
---@field count_real_listed_buffers fun(exclude_filetypes?: string[]): integer # Count listed buffers excluding plugins
---@field list_all_buffers_info fun(): BufInfo[] # Get metadata for all buffers
---@field list_listed_buffers_info fun(): BufInfo[] # Get metadata for listed buffers
---@field format_buffers_table fun(buftable: BufInfo[]): string # Format buffer table to string
---@field print_buffers_table fun(buftable: BufInfo[]): nil # Print buffer table to command line
---@field collect_all_buffer_info fun(): BufCollectedInfo # Aggregate all buffer information
---@field print_summary fun(): nil # Print buffer summary to command line
--
-- Window Utils (Flattened)
--
---@field count_listed_buffers_win fun(): integer # Count listed buffers (windows_utils version)
---@field list_all_buffers_info_win fun(): WinInfo[] # Get extended metadata for all buffers
---@field get_listed_buffer_ids fun(): integer[] # Get array of listed buffer IDs
---@field get_buffers_grouped_by_filetype fun(): table<string, integer[]> # Group buffers by filetype
---@field get_current_buffer_info fun(): WinInfo # Get current buffer metadata
---@field get_tabpage_buffers fun(tabnr?: integer): integer[] # Get buffers in tabpage
---@field format_buffers_report fun(): string # Format compact buffer report
---@field collect_all_state fun(): AggregatedState # Collect comprehensive state
---@field show_aggregated_state fun(silent?: boolean): string|nil # Print or return state
---@field collect_win_report fun(winid?: integer): WinReport # Collect window inspection report
--
-- Tab Utils (Flattened)
--
---@field list_tabs fun(): TabInfo[] # List all tabpages with metadata
---@field format_tab_one_line fun(info: TabInfo): string # Format tabpage to one line
---@field print_tabs fun(tabs?: TabInfo[]): nil # Pretty-print tabpages
---@field get_current_tab fun(): TabInfo|nil # Get current tabpage metadata
---@field get_tab_by_number fun(tabnr: integer): TabInfo|nil # Find tabpage by number
---@field is_single_tab fun(): boolean # Check if only one tab open
---@field collect_report fun(): TabReport # Collect tabpage report
--
-- =========================================================
-- Resize Guarded (Flattened)
-- =========================================================
--
---@field create_resize_callback fun(cmd: string, exclude_filetypes?: string[], exclude_names?: string[], lhs?: string): ResizeCallback # Create guarded resize callback
--
-- =========================================================
-- Capture (Flattened)
-- =========================================================
--
---@field capture_buf_win fun(cmd: string, opts?: BufWinCapture.Opts, cb?: fun(result: BufWinCapture.Results)): BufWinCapture.Results|nil # Capture buffers/windows after command
--
-- =========================================================
-- Safe Adjacent Buffer (Flattened)
-- =========================================================
--
---@field save_last_normal_buffer fun(): nil # Force-save last normal file buffer
--
-- =========================================================
-- Move current buffer to new tab
-- =========================================================
--
---@field move_current_buffer_to_new_tab Lib.BufWinTab.MoveBufToTab
---
-- =========================================================
-- Meta
-- =========================================================
--
---@field noop fun(): nil # No-operation function. Explicitly does nothing and returns nil.
---@field identity fun(v: any): any # Identity function. Returns the value it was given unchanged. Commonly used in functional pipelines as a default mapper or when a transformation hook is optional.
---@field always_true fun(): boolean # Constant-true predicate. Always returns true regardless of input. Useful as a default filter or guard function.
---@field always_false fun(): boolean # Constant-false predicate. Always returns false regardless of input. Useful as a disabling predicate or sentinel.
---@field const fun(value: any): fun(): any # Constant value generator. Returns a function that always yields the provided value. Useful for lazy defaults, dependency injection, or testing.
---@field raise fun(err: any): nil # Error passthrough helper. Always throws an error. LuaLS has no `never` type, so `nil` is used as a pragmatic substitute.
--
---
-- =========================================================
--- === Tables ===
-- =========================================================
---
---@field len fun(xs: any[]): integer # Return length using # operator (assumes dense array).
---
---@field clone fun(xs: any[]): any[] # Create a shallow copy of a dense array with preallocation.
---
---@field map fun(xs: any[], f: fun(v: any, i: integer, xs: any[]): any): any[] # Map over a dense array with preallocation. Returns new array with transformed values.
---
---@field filter fun(xs: any[], pred: fun(v: any, i: integer, xs: any[]): boolean): any[] # Filter a dense array. Prealloc then compact in one pass. Returns new array with elements matching predicate.
---
---@field reduce fun(xs: any[], f: fun(acc: any, v: any, i: integer): any, init: any): any # Reduce with explicit initial accumulator. Iterates left-to-right.
---
---@field partition fun(xs: any[], pred: fun(v: any, i: integer, xs: any[]): boolean): any[], any[] # Partition into {pass, fail} according to predicate. Returns two arrays: passing elements and failing elements.
---
---@field flatten fun(xss: any[][]): any[] # Flatten one level of nested arrays. Preallocates based on total size.
---
---@field unique fun(xs: any[]): any[] # Unique by equality (O(n) with set if primitives). Preserves first occurrence order.
---
---@field pluck fun(xs: table[], key: string): any[] # Pluck a field from array of tables, skipping nils. Returns array of extracted values.
---
---@field sorted fun(xs: any[], cmp: fun(a: any, b: any): boolean): any[] # Sort copy (stable-ish for small arrays); does not mutate input. Uses table.sort internally.
--
-- =========================================================
-- Core Table Utilities
-- =========================================================
--
---@field is_table fun(t: any): boolean # Check if value is a table type.
---
---@field is_array fun(t: any): boolean # Check if table is a dense array. Heuristic: consecutive integer keys starting at 1 with #t matching. Rejects mixed tables with extra non-integer keys.
---
---@field shallow_copy fun(t: table): table # Create a shallow copy of a table. Copies all key-value pairs but not nested tables.
---
---@field deep_copy fun(t: table): table # Create a deep copy of a table with cycle detection. Recursively copies all nested structures. Handles circular references via seen table.
---
---@field keys fun(t: table): string[] # Extract all string keys from a table. Returns array of string keys only.
---
---@field values fun(t: table): any[] # Extract all values from a table. Returns array of all values.
---
---@field invert_set fun(list: string[]): table<string, true> # Convert string array to set (table<string, true>). Non-string entries are skipped.
---
---@field pick fun(t: table, pick_keys: string[]): table # Create new table with only specified keys from source table.
---
---@field omit fun(t: table, omit_keys: string[]): table # Create new table excluding specified keys. Returns shallow copy without omitted keys.
---
---@field merge_shallow fun(dst: table, src: table): table # Merge src into dst (shallow). Mutates dst and returns it. Right-biased: src values overwrite dst.
---
---@field merge_deep fun(dst: table, src: table): table # Merge src into dst (deep). Recursively merges nested tables. Mutates dst and returns it.
---
---@field dedup_list fun(list: any[]): any[] # Deduplicate list preserving first occurrence order. Returns new array.
---
---@field slice fun(list: any[], i: integer, j?: integer): any[] # Extract slice from list [i..j]. Supports negative indices. Returns new array.
---
---@field unique_push fun(list: any[], v: any): boolean # Push value to list only if not already present. Mutates list. Returns true if added, false if duplicate.
---
---@field binary_search fun(list: any[], cmp: fun(a: any, b: any): boolean, x: any): integer, boolean # Binary search in sorted list. Returns (index, found). If not found, index is insertion point.
---
---@field group_by fun(list: any[], key: fun(item: any): any): table<any, any[]> # Group array elements by key function. Returns table mapping keys to arrays of matching elements.
---
---@field count_by fun(list: any[], key: fun(item: any): any): table<any, integer> # Count occurrences by key function. Returns table mapping keys to occurrence counts.
--
-- =========================================================
-- Dictionary Operations
-- =========================================================
--
---@field dict_clone fun(t: table): table # Shallow copy of a dictionary. Copies all key-value pairs.
---
---@field dict_pick fun(t: table, keys: any[]): table # Pick subset of keys from dictionary. Returns new table with only specified keys (if they exist in source).
---
---@field dict_omit fun(t: table, keys: any[]): table # Omit specified keys from dictionary. Returns new table excluding specified keys.
---
---@field dict_merge fun(a: table, b: table): table # Merge two dictionaries (right-biased). Returns new table with b's values overwriting a's for shared keys.
---
---@field dict_keys fun(t: table): any[] # Extract all keys as array. Preallocates output array for performance.
---
---@field dict_values fun(t: table): any[] # Extract all values as array. Preallocates output array for performance.
---
---@field dict_group_by fun(xs: any[], keyfn: fun(v: any): string|number): table<string|number, any[]> # Group array of items into dict of arrays by key function. Returns table mapping keys to arrays of items with that key.
--
-- =========================================================
-- Set Operations
-- =========================================================
--
---@field from_array fun(xs: any[]): table<any, true> # Create a set from an array. Returns table where each array element becomes a key with value true.
---
---@field to_array fun(s: table<any, true>): any[] # Convert set back to array (no order guarantee). Returns array of all keys in set.
---
---@field add fun(s: table<any, true>, v: any) # Add a value to the set. Mutates set in-place.
---
---@field add_all fun(s: table<any, true>, xs: any[]) # Add multiple values from an array to set. Mutates set in-place.
---
---@field remove fun(s: table<any, true>, v: any) # Remove a value from the set. Mutates set in-place.
---
---@field remove_all fun(s: table<any, true>, xs: any[]) # Remove multiple values from an array. Mutates set in-place.
---
---@field clear fun(s: table<any, true>) # Clear a set in-place. Removes all elements.
---
---@field has fun(s: table<any, true>, v: any): boolean # Check membership. Returns true if value is in set.
---
---@field size fun(s: table<any, true>): integer # Number of elements in set.
---
---@field copy fun(s: table<any, true>): table<any, true> # Shallow copy of a set. Returns new set with same elements.
---
---@field from_keys fun(t: table): table<any, true> # Build a set from the keys of a table. Returns set containing all keys as elements.
---
---@field union fun(a: table<any, true>, b: table<any, true>): table<any, true> # Union of two sets (new set). Returns set containing all elements from both sets.
---
---@field intersection fun(a: table<any, true>, b: table<any, true>): table<any, true> # Intersection of two sets (new set). Returns set containing only elements present in both sets. Optimized to iterate smaller set.
---
---@field difference fun(a: table<any, true>, b: table<any, true>): table<any, true> # Difference (a \ b): elements in a that are not in b (new set).
---
---@field symmetric_difference fun(a: table<any, true>, b: table<any, true>): table<any, true> # Symmetric difference: elements in a or b but not both (new set).
---
---@field is_subset fun(a: table<any, true>, b: table<any, true>): boolean # Subset test: a ⊆ b. Returns true if all elements of a are in b.
---
---@field is_superset fun(a: table<any, true>, b: table<any, true>): boolean # Superset test: a ⊇ b. Returns true if a contains all elements of b.
---
---@field equals fun(a: table<any, true>, b: table<any, true>): boolean # Equality test (same elements). Returns true if sets contain exactly the same elements.
---
---@field set_filter fun(s: table<any, true>, pred: fun(value: any): boolean): table<any, true> # Filter set by predicate; returns a new set containing only elements matching predicate.
---
---@field set_map fun(s: table<any, true>, fn: fun(value: any): any): table<any, true> # Map set to a new set of possibly different element type. Note: collisions (two inputs mapping to same output) are naturally deduplicated.
---
---@field iter fun(s: table<any, true>): fun(): any # Iterator over set elements (no guaranteed order). Returns iterator function.
--
-- =========================================================
-- Functional Programming Utilities
-- =========================================================
--
---@field fn_map fun(list: any[], fn: fun(item: any, index: integer): any): any[] # Map function over array. Returns new array with transformed elements. Pure function.
---
---@field fn_filter fun(list: any[], pred: fun(item: any, index: integer): boolean): any[] # Filter array by predicate. Returns new array containing only elements matching predicate. Pure function.
---
---@field fn_reduce fun(list: any[], init: any, fn: fun(acc: any, item: any, index: integer): any): any # Reduce array to single value. Starts with init accumulator and applies fn left-to-right.
---
---@field find fun(list: any[], pred: fun(item: any, index: integer): boolean): any|nil # Find first element matching predicate. Returns element or nil if not found.
---
---@field any fun(list: any[], pred: fun(item: any): boolean): boolean # Check if any element matches predicate. Short-circuits on first match.
---
---@field all fun(list: any[], pred: fun(item: any): boolean): boolean # Check if all elements match predicate. Short-circuits on first non-match.
---
---@field flat_map fun(list: any[], fn: fun(item: any): any[]): any[] # Map and flatten in one pass. Applies fn to each element (fn must return array) and concatenates results.
--
-- =========================================================
-- Safe Table Operations
-- =========================================================
--
---@field ensure_list fun(list: any[]|nil): any[] # Ensure value is a list. Returns input if it's a table, otherwise returns empty table.
---
---@field ensure_table fun(t: table|nil): table # Ensure value is a table. Returns input if it's a table, otherwise returns empty table.
---
---@field push fun(list: any[], v: any): integer # Push value to end of list. Mutates list. Returns new length.
---
---@field pop fun(list: any[]): any|nil # Remove and return last element of list. Mutates list. Returns nil if list is empty.
---
---@field insert_at fun(list: any[], idx: integer, v: any): boolean # Insert value at specific index. Mutates list. Returns true on success, false if index out of bounds [1..n+1].
---
---@field remove_at fun(list: any[], idx: integer): boolean # Remove element at specific index. Mutates list. Returns true on success, false if index out of bounds [1..n].
---
---@field snapshot_shallow fun(t: table): table # Create shallow snapshot of table. Useful for before/after comparisons or safe iteration during mutation.
---
---@field safe_ipairs fun(list: any[]): fun(): integer, any # Safe iterator over array. Captures length at start, preventing issues if list is mutated during iteration.
---
-- =========================================================
--- === Strings ===
-- =========================================================
-- lib.strings.core
---@field trim fun(s: any): string
---@field starts_with fun(s: string, prefix: string): boolean
---@field ends_with fun(s: string, suffix: string): boolean
---@field contains fun(s: string, needle: string): boolean
---@field split fun(s: string, sep: string): string[]
---@field join fun(parts: string[], sep: string): string
---@field replace_all fun(s: string, from: string, to: string): string
---@field normalize_ws fun(s: string): string|nil
---@field capitalize fun(s: string): string
---@field uncapitalize fun(s: string): string
---@field slugify fun(s: string): string
---@field kebab_case fun(s: string): string
---@field snake_case fun(s: string): string
---@field camel_case fun(s: string): string
---@field pad_start fun(s: string, width: integer): string
---@field pad_end fun(s: string, width: integer): string
---@field pad_center fun(s: string, width: integer): string
---@field indent fun(s: string, n: integer): string
---@field dedent fun(s: string): string
---@field is_empty_or_space fun(s: any): boolean
---@field count_lines fun(s: string): integer # Count lines in a string
-- lib.strings.links
---@field uri_decode fun(s: string): string
---@field normalize_anchor fun(s: string): string
---@field has_scheme fun(s: string): boolean
---@field is_web_url fun(s: string): boolean
---@field url_under_cursor fun(line: string, col: integer): string|nil
-- lib.strings.patterns
---@field escape_lua_magic fun(s: string): string
---@field find_plain fun(s: string, needle: string): integer|nil, integer|nil
---@field replace_plain fun(s: string, from: string, to: string): string
---@field surround fun(s: string, left: string, right: string): string
-- lib.strings.transform
---@field remove_prefix fun(s: string, list?: string[]): string
---@field trim fun(s: any): string
---@field slugify fun(s: string): string
---@field kebab_case fun(s: string): string
---@field snake_case fun(s: string): string
---@field camel_case fun(s: string): string
---@field capitalize fun(s: string): string
---@field uncapitalize fun(s: string): string
---@field normalize_ws fun(s: string): string|nil
---@field pad_start fun(s: string, width: integer): string
---@field pad_end fun(s: string, width: integer): string
---@field pad_center fun(s: string, width: integer): string
---@field indent fun(s: string, n: integer): string
---@field dedent fun(s: string): string
-- lib.strings.convert
---@field hex_to_string fun(hex: string): string
--
-- =========================================================
--- === Terminal ===
-- =========================================================
---
---@field terminal_escape fun(path: string): string # Cross-platform path escaping
---@field is_terminal_buf fun(bufnr: integer): boolean|nil # Checks if buffer is terminal
---@field delete_terminal_buf fun(bufnr: integer): boolean|nil # Deletes terminal buffer
---@field is_kitty fun(): nil # Return true if the current terminal environment is Kitty (Linux/macOS). Heuristics: KITTY_LISTEN_ON set OR TERM contains "kitty". Return true if the current terminal environment is Kitty (Linux/macOS). Heuristics: KITTY_LISTEN_ON set OR TERM contains "kitty".
---
-- =========================================================
--- === UI ===
-- =========================================================
---
--- Hover Select
---@field hover_select Lib.UI.HoverSelect # Hover select module
--- HL
---@field namespace fun(name: string): integer
---@field set fun(group: string, opts: Lib.Highlight.Opts, ns: string|integer|nil)-
---
-- =========================================================
--- === Notify ===
-- =========================================================
---@field create Lib.Notify.CreateFN
---@field safe Lib.Notify.Safe
---@field resolve_log_level fun(level?: LogLevel, default?: LogLevelNumber): integer # Resolve log level
---
-- =========================================================
--- === Lazy ===
-- =========================================================
---
---@field _loader fun(): table
---@field _value table|nil
---@field get? fun(): table Returns the loaded module. Loads it exactly once on first invocation.
---
-- =========================================================
--- === Memo ===
-- =========================================================
---
---@field lru Lib.Memo.Lru # Exposed LRU cache constructor module.
---@field memo Lib.Memo.Memo # Exposed memoization helper module.
---@field fn fun(func: fun(...): any, opts: table<string, any>|nil): fun(...): any # Convenience function: memoize with default settings Delegates to memo.memoize but provides shorter syntax.
---
-- =========================================================
--- === Time ===
-- =========================================================
---
---@field time_diff fun(): Lib.Time.TimeDiff # Create time diff instance
---
-- =========================================================
--- === Normalize ===
-- =========================================================
---
---@field to_bool fun(v: any): boolean|nil
--- Convert value into a boolean using loose parsing rules.
--- Accepts: booleans directly, numbers 0/1, strings "true/false/yes/no/on/off/1/0" (case-insensitive).
--- Returns nil for any value that cannot be interpreted as boolean.
---
---@field to_int fun(v: any, min?: integer, max?: integer): integer|nil
--- Convert value to integer with optional clamping to [min, max] range.
--- Truncates towards zero for non-integer numbers.
--- Returns nil if conversion fails.
---
---@field to_float fun(v: any, min?: number, max?: number, precision?: integer): number|nil
--- Convert value to float with optional clamping and precision rounding.
--- precision: Number of fractional digits to keep (>=0), nil = no rounding.
--- Returns nil if conversion fails.
---
---@field to_string fun(v: any, allow_empty?: boolean, do_trim?: boolean): string|nil
--- Return string if non-empty, optionally trimming whitespace.
--- allow_empty: If false/nil, empty strings return nil.
--- do_trim: If true, trim leading/trailing whitespace.
---
---@field to_enum fun(v: any, allowed: Lib.Normalize.StringList, case_insensitive?: boolean): string|nil
--- Map a value to an enum entry, matching against allowed values.
--- By default performs case-insensitive matching; returns original allowed value on match.
--- Returns nil if no match found.
---
---@field to_string_list fun(v: any, opts?: Lib.Normalize.StringListOpts): Lib.Normalize.StringList|nil
--- Convert value into a list of strings.
--- Accepts strings (split by separator) or tables (filtered to string entries).
--- Empty results return nil.
---
---@field to_argv fun(v: any): Lib.Normalize.StringList|nil
--- Convert shell-like command string or argv table into argv format.
--- Supports simple double-quoted segments; does not resolve escapes comprehensively.
--- Returns nil if any array element is non-string or empty.
---
---@field to_diagnostic_severity fun(v: any): integer|nil
--- Map user severity to vim.diagnostic.severity constant.
--- Accepts: "error/err", "warn/warning", "info", "hint", "all"/"" (returns nil for all/empty).
--- Numeric values pass through unchanged.
---
---@field to_log_level fun(v: any): integer|nil
--- Map user log level to vim.log.levels constant.
--- Accepts: "trace", "debug", "info", "warn", "error", "off" (returns nil for off).
--- Numeric values pass through unchanged.
---
---@field to_path fun(v: any, type_filter?: string, must_exist?: boolean): string|nil
--- Normalize filesystem path and optionally verify existence and type.
--- type_filter: Required path type: "file", "directory", or nil (any type).
--- must_exist: If true, path must exist and match type_filter.
--- Uses vim.fs.normalize when available, otherwise provides fallback normalization.
---
-- =========================================================
-- Validators with (ok, val, err) Pattern
-- =========================================================
---
---@field as_int fun(name: string, v: any, min: integer, allow_nil: boolean): boolean, integer|nil, string|nil
--- Validate that a value is an integer meeting minimum bound requirements.
--- Returns: (ok, val, err)
--- Contract:
---   • nil + allow_nil=true  → ok=true, val=nil, err=nil (caller keeps default)
---   • nil + allow_nil=false → ok=false, val=nil, err="<name> is required"
---   • non-integer           → ok=false, err="<name> must be an integer"
---   • value < min           → ok=false, err="<name> must be ≥ <min>"
---   • otherwise             → ok=true, val=<integer>, err=nil
---
---@field as_bool fun(name: string, v: any): boolean, boolean|nil, string|nil
--- Validate that a value is strictly boolean (true/false).
--- Returns: (ok, val, err)
--- Only Lua booleans are accepted; strings like "true"/"false" are NOT coerced.
--- For permissive conversion, use to_bool() + apply_bool_loose().
---
---
-- =========================================================
-- Utility Functions
-- =========================================================
---
---@field trim fun(s: any): string
--- Trim leading and trailing ASCII whitespace from string.
--- Returns empty string if input is not a string.
---
---@field clamp fun(n: number, min?: number, max?: number): number
--- Clamp number into [min, max] range (inclusive).
--- Nil min/max values are ignored.
---
---@field coalesce fun(...: any): any
--- Return the first non-nil argument.
--- Returns nil if all arguments are nil.
---
---@field normalize_path fun(p: any): string
--- Normalize filesystem path using Neovim facilities if available.
--- Uses vim.fs.normalize when present, otherwise provides fallback that:
---   • Collapses consecutive slashes
---   • Strips trailing slash (except for root)
--- Returns empty string if input is invalid.
---
---@field path_kind fun(p: string): string
--- Determine path type using libuv if available.
--- Returns: "file", "directory", or "" (does not exist/unavailable).
---
---@field dedup_strings fun(list: Lib.Normalize.StringList): Lib.Normalize.StringList
--- Deduplicate string list while preserving first occurrence order.
--- Non-string entries are filtered out.
---
---
--- === Nvim ===
---@field has_exec fun(bin: string): boolean
---@field simple_echo fun(msg: string, hl: string|nil, is_error: boolean|nil): integer|string # This module returns a single function that echoes messages using vim.api.nvim_echo
---
-- =========================================================
--- === JSON ====
-- =========================================================
---
--- Decode
---
---@field json_is_array_like fun(v: any): boolean # Prüft, ob ein Wert eine array-ähnliche Tabelle ist. Erlaubt sind ausschließlich zusammenhängende positive Integer-Keys beginnend bei 1 (Lua-Array-Semantik). Gibt false für Maps, Sparse-Arrays oder Nicht-Tabellen zurück
---
---@field json_table_to_string_array fun(tbl: table): string[] # Konvertiert eine Tabelle in ein `string[]`.
--- * Array-ähnliche Tabellen: jedes Element wird per `tostring` übernommen.
--- * Nicht-array-ähnliche Tabellen: Keys werden stabil sortiert und
---   als `"key: value"`-Strings serialisiert.
--- * Verschachtelte Tabellen werden mittels `vim.inspect` dargestellt.
---
---@field json_ensure_string_array fun(v: any): string[] # Erzwingt ein `string[]` aus beliebigem Input.
--- * table   → `table_to_string_array`
--- * string  → Aufteilung an Newlines (`vim.split`)
--- * scalar  → Einzel-Array mit `tostring(v)`
--- Garantiert immer ein nicht-nil `string[]`.

return {}
