---@meta
---@module '@types.lsp'
--- Type definitions for vim.lsp (missing from Neovim's builtin types)

---@class vim.lsp.Client
---@field id integer Unique client ID
---@field name string Client name (e.g., "lua_ls", "ts_ls")
---@field offset_encoding? string Position encoding ("utf-8", "utf-16", "utf-32")
---@field config table Client configuration
---@field config.root_dir? string Project root directory
---@field config.cmd? string[] Command used to start the server
---@field config.settings? table Server-specific settings
---@field server_capabilities table Server capabilities (methods it supports)
---@field server_capabilities.documentFormattingProvider? boolean|table
---@field server_capabilities.documentRangeFormattingProvider? boolean|table
---@field server_capabilities.codeActionProvider? boolean|table
---@field server_capabilities.completionProvider? table
---@field server_capabilities.definitionProvider? boolean|table
---@field server_capabilities.referencesProvider? boolean|table
---@field server_capabilities.hoverProvider? boolean|table
---@field server_capabilities.signatureHelpProvider? table
---@field server_capabilities.documentSymbolProvider? boolean|table
---@field server_capabilities.workspaceSymbolProvider? boolean|table
---@field server_capabilities.codeLensProvider? table
---@field server_capabilities.inlayHintProvider? table
---@field server_capabilities.semanticTokensProvider? table
---@field workspace_folders? table[] Workspace folders
---@field request fun(self: vim.lsp.Client, method: string, params: table, handler: function, bufnr: integer): boolean, integer? Send LSP request
---@field request_sync fun(self: vim.lsp.Client, method: string, params: table, timeout_ms?: integer, bufnr?: integer): table?, string? Send synchronous LSP request
---@field notify fun(self: vim.lsp.Client, method: string, params: table): boolean Send LSP notification
---@field cancel_request fun(self: vim.lsp.Client, id: integer): boolean Cancel pending request
---@field stop fun(self: vim.lsp.Client, force?: boolean) Stop the client
---@field is_stopped fun(self: vim.lsp.Client): boolean Check if client is stopped
---@field supports_method fun(self: vim.lsp.Client, method: string, opts?: table): boolean Check if client supports a method

---@class vim.lsp.get_clients.Filter
---@field id? integer Filter by client ID
---@field bufnr? integer Filter by buffer number
---@field name? string Filter by client name
---@field method? string Filter by supported method

---@class vim.lsp.ClientConfig
---@field name? string Client name
---@field cmd? string[] Command to start server
---@field cmd_cwd? string Working directory for cmd
---@field cmd_env? table<string, string> Environment variables
---@field root_dir? string|fun(filename: string, bufnr: integer): string? Project root
---@field filetypes? string[] File types to attach to
---@field autostart? boolean Auto-start on matching filetype
---@field single_file_support? boolean Support single files without project
---@field on_init? fun(client: vim.lsp.Client, result: table): boolean
---@field on_attach? fun(client: vim.lsp.Client, bufnr: integer)
---@field on_exit? fun(code: integer, signal: integer, client_id: integer)
---@field before_init? fun(params: table, config: table)
---@field capabilities? table Client capabilities
---@field handlers? table<string, function> Custom LSP handlers
---@field settings? table Server-specific settings
---@field init_options? table Server initialization options
---@field workspace_folders? table[] Initial workspace folders

---@class vim.lsp.start.Opts
---@field name? string Client name
---@field cmd string[] Command to start server
---@field cmd_cwd? string Working directory
---@field cmd_env? table<string, string> Environment
---@field root_dir? string Project root
---@field capabilities? table Client capabilities
---@field on_init? fun(client: vim.lsp.Client, result: table): boolean
---@field on_attach? fun(client: vim.lsp.Client, bufnr: integer)
---@field on_exit? fun(code: integer, signal: integer, client_id: integer)
---@field handlers? table<string, function>
---@field settings? table
---@field init_options? table

-- Extend vim.lsp namespace
---@class vim.lsp
---@field start fun(config: vim.lsp.start.Opts, opts?: table): vim.lsp.Client? Start LSP client
---@field stop_client fun(client_id: integer|integer[], force?: boolean) Stop LSP client(s)
---@field get_client_by_id fun(client_id: integer): vim.lsp.Client? Get client by ID
---@field get_clients fun(filter?: vim.lsp.get_clients.Filter): vim.lsp.Client[] Get active clients
---@field get_active_clients fun(filter?: table): vim.lsp.Client[] Get active clients (deprecated)
---@field buf_attach_client fun(bufnr: integer, client_id: integer): boolean Attach client to buffer
---@field buf_detach_client fun(bufnr: integer, client_id: integer) Detach client from buffer
---@field buf_is_attached fun(bufnr: integer, client_id: integer): boolean Check if attached
---@field buf_notify fun(bufnr: integer, method: string, params: table): boolean Send notification
---@field buf_request fun(bufnr: integer, method: string, params: table, handler: function): boolean, integer? Send request
---@field buf_request_sync fun(bufnr: integer, method: string, params: table, timeout_ms?: integer): table<integer, {err: table?, result: any}>? Send synchronous request
---@field buf_request_all fun(bufnr: integer, method: string, params: table, handler: function): table<integer, integer> Send request to all clients

-- vim.lsp.buf format options
---@class vim.lsp.buf.format.Opts
---@field timeout_ms? integer Timeout in milliseconds
---@field bufnr? integer Buffer number to format
---@field filter? fun(client: vim.lsp.Client): boolean Filter function for clients
---@field async? boolean Format asynchronously
---@field id? integer Format with specific client ID
---@field name? string Format with specific client name
---@field range? table Format specific range

---@class vim.lsp.buf.code_action.Opts
---@field context? table Code action context
---@field filter? fun(action: table): boolean Filter function
---@field apply? boolean Apply first action automatically
---@field range? table Specific range

---@class vim.lsp.buf.rename.Opts
---@field filter? fun(client: vim.lsp.Client): boolean Filter function
---@field name? string New name (if not provided, will prompt)

-- vim.lsp.buf functions
---@class vim.lsp.buf
---@field format fun(opts?: vim.lsp.buf.format.Opts) Format buffer
---@field hover fun() Show hover information
---@field signature_help fun() Show signature help
---@field definition fun(opts?: table) Go to definition
---@field declaration fun(opts?: table) Go to declaration
---@field type_definition fun(opts?: table) Go to type definition
---@field implementation fun(opts?: table) Go to implementation
---@field references fun(context?: table, opts?: table) Show references
---@field document_symbol fun(opts?: table) Show document symbols
---@field workspace_symbol fun(query?: string, opts?: table) Show workspace symbols
---@field code_action fun(opts?: vim.lsp.buf.code_action.Opts) Show code actions
---@field rename fun(new_name?: string, opts?: vim.lsp.buf.rename.Opts) Rename symbol
---@field incoming_calls fun() Show incoming calls
---@field outgoing_calls fun() Show outgoing calls

return {}
