return {}
-- ---@module 'plugins.dap_old'
-- --- Superseded by StefanBartl/dap.nvim (see lua/plugins/personal/init.lua),
-- --- which wraps these same upstream plugins with adapter/config registration,
-- --- signs/highlights, and keymaps migrated from the former lua/wkddap module.

-- ---@type LazyPluginSpec[]
-- return {
--   -- Core DAP plugin
--   {
--     "mfussenegger/nvim-dap",
--     dependencies = {
--       "jbyuki/one-small-step-for-vimkind",
--     },
--     lazy = true,
--     keys = {
--       { "<leader>dc", function() require("dap").continue() end, desc = "[DAP] Continue" },
--       { "<leader>ds", function() require("dap").step_over() end, desc = "[DAP] Step Over" },
--       { "<leader>di", function() require("dap").step_into() end, desc = "[DAP] Step Into" },
--       { "<leader>do", function() require("dap").step_out() end, desc = "[DAP] Step Out" },
--       { "<leader>dt", function() require("dap").terminate() end, desc = "[DAP] Terminate" },
--       { "<leader>dr", function() require("dap").restart() end, desc = "[DAP] Restart" },
--       { "<leader>db", function() require("dap").toggle_breakpoint() end, desc = "[DAP] Toggle Breakpoint" },
--     },
--     config = function()
--       -- signs/highlights/adapters/configurations previously inlined here now
--       -- live in dap.nvim: lua/dap_nvim/{ui,adapters,configurations}/*
--     end,
--   },

--   -- DAP UI
--   {
--     "rcarriga/nvim-dap-ui",
--     dependencies = {
--       "mfussenegger/nvim-dap",
--       "nvim-neotest/nvim-nio",
--     },
--   },

--   -- Virtual Text
--   {
--     "theHamsta/nvim-dap-virtual-text",
--     dependencies = { "mfussenegger/nvim-dap" },
--   },
-- }
