---@module 'plugins.ai.anthropic'
---
--- Anthropic provider configuration for Avante.
---
--- This module contains the complete provider configuration for the
--- Anthropic API. It is intentionally separated from the Lazy.nvim
--- plugin specification, allowing it to be reused by multiple AI
--- integrations (for example Avante, CodeCompanion or custom tooling).
---
--- The API key is expected to be provided through the standard `ANTHROPIC_API_KEY` environment variable

---@type AvanteAnthropicConfig
local M = {

  ----------------------------------------------------------------------------
  -- Provider Selection
  ----------------------------------------------------------------------------

  ---Selects the active AI provider.
  ---
  ---The value must match one of the entries defined in the `providers`
  ---table below.
  ---
  ---Examples:
  ---  "claude"
  ---  "ollama"
  ---  "openai"
  provider = "claude",

  ----------------------------------------------------------------------------
  -- Provider Definitions
  ----------------------------------------------------------------------------

  providers = {

    claude = {

      ---Anthropic API endpoint.
      ---
      ---Normally there is no reason to modify this value unless
      ---using a proxy or a self-hosted gateway.
      endpoint = "https://api.anthropic.com",

      ---Claude model identifier.
      ---
      ---Common examples:
      ---  claude-sonnet-4
      ---  claude-opus-4
      ---  claude-haiku-4
      model = "claude-sonnet-4",

      ---Maximum time (milliseconds) to wait for a response.
      ---
      ---Increase this value when generating large files or using
      ---slow internet connections.
      timeout = 30000,

      ---Controls response randomness.
      ---
      ---0.0 = deterministic
      ---1.0 = more creative
      ---
      ---For programming tasks a value between 0.0 and 0.2 is
      ---generally recommended.
      temperature = 0,

      ---Maximum number of output tokens generated by Claude.
      ---
      ---Larger values allow longer responses but may increase
      ---latency and API costs.
      max_tokens = 8192,
    },
  },

  ----------------------------------------------------------------------------
  -- Behaviour
  ----------------------------------------------------------------------------

  behaviour = {

    ---Automatically request code suggestions while typing.
    ---
    ---Disabling this reduces API requests and token usage.
    auto_suggestions = false,

    ---Automatically create highlight groups when required.
    ---
    ---Recommended unless custom highlight groups are managed
    ---externally.
    auto_set_highlight_group = true,

    ---Automatically register default keymaps.
    ---
    ---Disable when all mappings are managed manually.
    auto_set_keymaps = false,

    ---Automatically apply generated diffs.
    ---
    ---When disabled the diff can be reviewed before applying.
    auto_apply_diff_after_generation = false,

    ---Allow pasting directly from the system clipboard.
    ---
    ---Useful when interacting with external terminals or browsers.
    support_paste_from_clipboard = true,
  },

  ----------------------------------------------------------------------------
  -- Windows
  ----------------------------------------------------------------------------

  windows = {

    ---Sidebar location.
    ---
    ---Allowed values:
    ---  "left"
    ---  "right"
    position = "right",

    ---Sidebar width in editor columns.
    width = 40,

    ---Wrap long lines inside chat windows.
    wrap = true,

    sidebar_header = {

      ---Display a title above the sidebar.
      enabled = true,

      ---Use rounded borders when supported by the terminal.
      rounded = true,
    },
  },

  ----------------------------------------------------------------------------
  -- Diff
  ----------------------------------------------------------------------------

  diff = {

    ---Automatically jump to the first changed section after
    ---generating a diff.
    autojump = true,

    ---Command used to display the quickfix/location list.
    ---
    ---Examples:
    ---  "copen"
    ---  "lopen"
    list_opener = "copen",
  },

  ----------------------------------------------------------------------------
  -- Key Mappings
  ----------------------------------------------------------------------------

  mappings = {

    ---Open a new AI chat.
    ask = "<leader>aa",

    ---Edit the current visual selection or buffer.
    edit = "<leader>ae",

    ---Refresh the current conversation.
    refresh = "<leader>ar",

    ---Move cursor focus to the Avante sidebar.
    focus = "<leader>af",

    ---Cancel the currently running AI request.
    stop = "<leader>as",
  },
}

return M
